- since wxWindows+debugger+readline is a combination that currently doesn't   work (control-C kills process instead of returning to debugger prompt), give   a configure-time error if they are enabled together.  If we can fix the   signal problem in readline, this check can be removed.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -750,6 +750,7 @@ AC_ARG_ENABLE(readline,
     ]
  )
 
+use_readline=0
 AC_MSG_CHECKING(whether to use readline)
 if test "$want_readline" = yes; then
   if test "$bx_debugger" = 1; then
@@ -757,10 +758,12 @@ if test "$want_readline" = yes; then
       AC_MSG_RESULT(yes)
       AC_DEFINE(HAVE_LIBREADLINE, 1)
       READLINE_LIB="-lreadline"
+      use_readline=1
     elif test "$rl_with_curses_ok" = yes; then
       AC_MSG_RESULT(yes)
       AC_DEFINE(HAVE_LIBREADLINE, 1)
       READLINE_LIB="-lreadline -lcurses"
+      use_readline=1
     else
       AC_MSG_RESULT(no)
       echo WARNING: The readline library was disabled because it was not found.
@@ -1271,6 +1274,15 @@ elif test "$with_wx" = yes; then
   # wxwindows is the only one without control.o in GUI_OBJS
   GUI_OBJS='$(GUI_OBJS_WX)'
   GUI_LINK_OPTS='$(GUI_LINK_OPTS_WX)'
+  # using debugger with readline is failing due to thread/signal handler
+  # problems.
+  if test "$use_readline" = 1 -a "$bx_debugger" = 1; then
+    echo ERROR: You have selected wxWindows, the debugger, and the readline 
+    echo library.  This combination is known to trigger problems with SIGINT 
+    echo handling.  Please run configure again with --disable-readline to 
+    echo correct this.
+    exit 1
+  fi
 else
   AC_MSG_RESULT(none)
   AC_DEFINE(BX_WITH_NOGUI, 1)
