- rfb gui needs the socket function. on solaris, you need to link with   -lsocket to get it.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1486,6 +1486,18 @@ if test "$use_curses" = yes; then
   fi
 fi
 
+if test "$with_rfb" = yes -a "$cross_configure" = 0; then
+  # we need the socket function. if cross configuring, don't bother.
+  AC_CHECK_FUNCS(socket, have_socket=yes)
+  if test "$have_socket" != yes; then
+    AC_CHECK_LIB(socket, socket, 
+      [ GUI_LINK_OPTS_RFB="$GUI_LINK_OPTS_RFB -lsocket" ], 
+      [
+        echo 'ERROR: socket function required for RFB compile'
+        exit 1
+      ])
+  fi
+fi
 
 # The ACX_PTHREAD function was written by 
 # Steven G. Johnson <stevenj@alum.mit.edu> and 
