Move MMX to be runtime option

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -578,6 +578,10 @@ AC_ARG_ENABLE(cpu-level,
      echo "ERROR: with >1 processor, use --enable-cpu-level=6"
      exit 1
    fi
+   if test "$use_x86_64" = 1 -a "$enableval" -lt 6; then
+     echo "ERROR: --enable-cpu-level=6 required for x86-64 emulation"
+     exit 1
+   fi
   ],
   [
     AC_MSG_RESULT(6)
@@ -1406,28 +1410,6 @@ AC_ARG_ENABLE(vmx,
 if test "$support_vmx" -lt 0 -a "$bx_cpu_level" -lt 6; then
   AC_MSG_ERROR([for VMX support the CPU level must be set to 6])
 fi
-
-AC_MSG_CHECKING(for MMX support)
-AC_ARG_ENABLE(mmx,
-  [  --enable-mmx                      MMX support],
-  [if test "$enableval" = yes; then
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_MMX, 1)
-   elif test "$enableval" = no; then
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_MMX, 0)
-   fi
-   ],
-  [
-    if test "$bx_cpu_level" -ge 5; then
-      AC_MSG_RESULT(yes)
-      AC_DEFINE(BX_SUPPORT_MMX, 1)
-    else
-      AC_MSG_RESULT(no)
-      AC_DEFINE(BX_SUPPORT_MMX, 0)
-    fi
-    ]
-  )
 
 AC_MSG_CHECKING(for 3DNow! support)
 AC_ARG_ENABLE(3dnow,
